/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
  }
}
